FROM gradle:5.6.4-jdk8 AS build_env
USER gradle
COPY --chown=gradle:gradle . /home/gradle/kalki-db
RUN mkdir -p /home/gradle/src/
RUN cp /home/gradle/kalki-db/gradle.properties /home/gradle/src/
WORKDIR /home/gradle/kalki-db
ARG SKIP_TESTS=""
RUN gradle build publishToMavenLocal $SKIP_TESTS --no-daemon
