FROM gradle:5.6.4-jdk8 AS build_env
COPY --chown=gradle:gradle . /home/gradle/kalki-db
RUN mkdir -p /home/gradle/src/
RUN mkdir -p /logs/
RUN cp /home/gradle/kalki-db/gradle.properties /home/gradle/src/
WORKDIR /home/gradle/kalki-db
RUN gradle build publishToMavenLocal --no-daemon
